### ISSUE TITLE
Cant login with valid credentials 

### ISSUE THREAD

**Issue by ghost** [C0D3D3V/Moodle-Crawler#22]
I'm trying to get this script to work with this site `https://aules.edu.gva.es/moodle/login/index.php` from Spain, but I'm not getting any luck even tho I have a valid username and password that i can use from the browser.
I'm getting `cannot connect to moodle or Moodle has changed. Crawler is not logged in. Check your login data.`

**Comment by C0D3D3V** [comment]
I will make a update in a few hours, so that logintokens gets automaticly detected.
But for now you can set uselogintoken = true in the config

**Comment by SrSands** [comment]
Tried and i got this.

`19:13:52 Moodle Crawler started working.
19:13:52 Try to copy logintoken!
19:13:52 Warning: Found 2 forms!
Traceback (most recent call last):
  File "moodleCrawler.py", line 1488, in <module>
    if inputLogintoken is None or inputLogintoken[0] is None:
IndexError: list index out of range`

**Comment by C0D3D3V** [comment]
I'm very sorry. Thats a true issue :(  I will fix it now :)

**Comment by SrSands** [comment]
I'm getting this now

00:23:22 Logintoken: [my token]
Traceback (most recent call last):
  File "moodleCrawler.py", line 1686, in <module>
    logFileWriter = open(crawlqHistoryFile, 'ab')
NameError: name 'crawlqHistoryFile' is not defined

**Comment by C0D3D3V** [comment]
ow, lol, thank you!
 I added that bug a few days before... I will remove it in a few min.

**Comment by C0D3D3V** [comment]
done
