### ISSUE TITLE
Credentials don't work with a redirect login

### ISSUE THREAD

**Issue by monoflo** [C0D3D3V/Moodle-Crawler#3]
[UMass Amherst Moodle](https://moodle.umass.edu/)

**Comment by C0D3D3V** [comment]
Yes, I saw this bug last week too. 
I will try to fix it next week.

**Comment by monoflo** [comment]
Any luck?

**Comment by C0D3D3V** [comment]
Can you please check if it works now?

If it doesn't  work, please set the 'loglevel' to 5 and post here the log.

**Comment by C0D3D3V** [comment]
I'm not sure if I fixed it, I will add one more fix tomorrow. 
But you can try to set the authentication url to: https://moodle.umass.edu/login/index.php

**Comment by C0D3D3V** [comment]
I added now an option for the URL of the moodle installation. Try to set 'baseurl' to 'https://moodle.umass.edu/'
